### PR TITLE
Update deb-get to add support for Cisco Webex

### PR DESCRIPTION
**Pull request by charles-hood**
Add support for Cisco Webex deb

### CODE REVIEW

**Comment by charles-hood** [comment]
This closes issue #7

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
The Webex .deb is 300MB. Everytime `deb-get` needs to check the published version of Webex to determine if it should offer an update, it will need to download 300MB.

I don't think that is acceptable :disappointed:

**Comment by flexiondotorg** [comment]
The Webex release notes do include the version numbers.

* https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes#Cisco_Reference.dita_f9f89a28-7cde-4185-9215-d668ba90ad93

Perhaps the version number for Linux can be extracted from that page?

**Comment by flexiondotorg** [comment]
This seems to work:

```bash
curl -s "https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes" | grep "<p class=\"p\">Linux—" | head -n1 | cut -d'>' -f2 | cut -d'<' -f1 | sed 's/Linux—//'
```

**Comment by charles-hood** [comment]
Or do a partial download of the deb using the range parameter of curl?

'curl -r 0-9999'

**Pull request merged**
