### PR TITLE
feat: Add firefox{,-beta,-devediton,-nightly}

### PR DESCRIPTION
**Pull request by rasa**
Tested all five of apps in this PR locally, and they all installed fine, on mantic 23.10. 

Note that this PR is a superset of #893.

This page was super helpful:
https://hacks.mozilla.org/2023/11/firefox-developer-edition-and-beta-try-out-mozillas-deb-package/

### CODE REVIEW

**Review by philclifford — CHANGES_REQUESTED** [review]
You must set APT_LIST_NAME=<the same thing> (maybe "mozilla_org" )
for the entries that share the same repo and key or you get apt complaining (and failing) because of the clashing of "different" (but identical) repository signing keys for the one repo.

Also it would be a good idea to have seperate PRs for -beta and -nightly (in case of rigid views on the acceptability criteria precluding accepting the ppa or -devedition )

**Comment by rasa** [comment]
> You must set APT_LIST_NAME= (maybe "mozilla_org" ) for the entries that share the same repo and key or you get apt complaining (and failing) because of the clashing of "different" (but identical) repository signing keys for the one repo.

@philclifford Currently, for the packages that share the same repo and key, each package has a different `APT_LIST_NAME`. Are you suggesting setting `APT_LIST_NAME` to `mozilla_org` for all of them?

I'm happy to make that change, but I'm not sure why, as I manually installed all 5 packages  individually, and didn't see any errors when installing, or updating, them.

> Also it would be a good idea to have separate PRs for -beta and -nightly (in case of rigid views on the acceptability criteria precluding accepting the ppa or -devedition )

So, you're suggesting each package be it's own PR? If so, happy to oblige.

**Comment by philclifford** [comment]
This is what happens if two entries share the same repo and key:
```
testing:/etc/deb-get/99-local.d$ grep -e APT_LIST  -e KEY firefox* 
firefox-beta:GPG_KEY_ID="C0BA5CE6DC6315A3"
firefox-beta:APT_LIST_NAME="mozilla-beta"
firefox-nightly:GPG_KEY_ID="C0BA5CE6DC6315A3"
firefox-nightly:APT_LIST_NAME="mozilla-nightly"
testing:/etc/deb-get/99-local.d$ deb-get  install firefox*
  [+] Including local package firefox-beta
  [+] Including local package firefox-nightly
  [!] Please consider contributing back new entries, an issue (or raise a PR) directly at https://github.com/wimpysworld/deb-get/pulls
gpg: keybox '/usr/share/keyrings/mozilla-beta-archive-keyring.gpg' created
gpg: key C0BA5CE6DC6315A3: public key "Artifact Registry Repository Signer <artifact-registry-repository-signer@google.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
  [+] Updating: /etc/apt/sources.list.d/mozilla-beta.list
Get:1 https://packages.mozilla.org/apt mozilla InRelease [1,350 B]
Get:2 https://packages.mozilla.org/apt mozilla/main all Packages [3,336 kB]
Get:3 https://packages.mozilla.org/apt mozilla/main i386 Packages [59.9 kB]
Get:4 https://packages.mozilla.org/apt mozilla/main amd64 Packages [60.1 kB]
Fetched 3,457 kB in 3s (1,254 kB/s)
Reading package lists... Done
E: Conflicting values set for option Signed-By regarding source https://packages.mozilla.org/apt/ mozilla: /usr/share/keyrings/mozilla-beta-archive-keyring.gpg != /usr/share/keyrings/mozilla-archive-keyring.gpg
E: The list of sources could not be read.
gpg: keybox '/usr/share/keyrings/mozilla-nightly-archive-keyring.gpg' created
gpg: key C0BA5CE6DC6315A3: public key "Artifact Registry Repository Signer <artifact-registry-repository-signer@google.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
  [+] Updating: /etc/apt/sources.list.d/mozilla-nightly.list
Hit:1 https://packages.mozilla.org/apt mozilla InRelease
Reading package lists... Done
E: Conflicting values set for option Signed-By regarding source https://packages.mozilla.org/apt/ mozilla: /usr/share/keyrings/mozilla-nightly-archive-keyring.gpg != /usr/share/keyrings/mozilla-archive-keyring.gpg
E: The list of sources could not be read.
```
`apt` will not accept conflicting signatures for the same source (even if the actual key is identical).

In this case both fail and list changes are rolled back with neither installed.  If they are given the same APT_LIST_NAME (mozilla in my test case):

```
$ deb-get  install firefox-beta firefox-nightly
  [+] Updating: /etc/apt/sources.list.d/mozilla.list
Hit:1 https://packages.mozilla.org/apt mozilla InRelease
Reading package lists... Done
Selecting previously unselected package firefox-beta.
(Reading database ... 474311 files and directories currently installed.)
Preparing to unpack .../firefox-beta_123.0b9~build1_amd64.deb ...
Unpacking firefox-beta (123.0b9~build1) ...
Setting up firefox-beta (123.0b9~build1) ...
Processing triggers for bamfdaemon (0.5.6+22.04.20220217-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
[...]
  [+] Updating: /etc/apt/sources.list.d/mozilla.list
Hit:1 https://packages.mozilla.org/apt mozilla InRelease
Reading package lists... Done
Selecting previously unselected package firefox-nightly.
(Reading database ... 474395 files and directories currently installed.)
Preparing to unpack .../firefox-nightly_124.0a1~20240209114116_amd64.deb ...
Unpacking firefox-nightly (124.0a1~20240209114116) ...
Setting up firefox-nightly (124.0a1~20240209114116) ...
[...]
$ deb-get show firefox-beta firefox-nightly
Firefox Beta
  Package:	firefox-beta
  Repository:	81-betas
  Updater:	apt
  Installed:	123.0b9~build1
[...]
Firefox Nightly
  Package:	firefox-nightly
  Repository:	81-betas
  Updater:	apt
  Installed:	124.0a1~20240209114116
[...]
```

**Comment by philclifford** [comment]
You can see the same failure in the failing test log https://github.com/wimpysworld/deb-get/actions/runs/7705276279/job/20998935351?pr=966 (while it remains there)

**Comment by philclifford** [comment]
I would suggest a separate PR ( or two - one for each) for `firefox-beta` and `firefox-nightly`. I'd advocate for merging all (because there are also stable and esr options already available) but it makes it easier to deal separately with merging (or reverting) the unstable options. For me moving -beta and -nightly into one  separate PR is the best bet.

**Comment by rasa** [comment]
@philclifford PRs coming soon. Thx for your feedback.

**Pull request closed without merging**
