### PR TITLE
deb-get: add simple-pwgen

### PR DESCRIPTION
**Pull request by hsbasu**

### CODE REVIEW

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Please correct the `PRETTY_NAME`

**Comment by hsbasu** [comment]
> Please correct the `PRETTY_NAME`

Oops! Now corrected. Thanks.

**Comment by hsbasu** [comment]
@flexiondotorg The gui package `simple-pwgen` depends on the cli backend `python3-simple-pwgen`. Would deb-get be able to resolve the dependency?

**Comment by flexiondotorg** [comment]
@hsbasu Where is `python3-simple-pwgen` published?

**Comment by hsbasu** [comment]
The file is on github release page

**Comment by natanjunges** [comment]
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

**Pull request closed without merging**
