### PR TITLE
deb-get: add icaclient

### PR DESCRIPTION
**Pull request by arif-ali**
First stab at this.

I need the FILE variable to be visible to the other functions that is being used, and the as the download URL would look similar to

http://downloads.citrix.com/20613/icaclient_22.3.0.24_amd64.deb?__gda__=exp=1651226310~acl=/*~hmac=177b2a403e01e0199fcb32f5e3b0fa2e995657b5c31322e07afc96e593f73cf5

I can get 

```
sudo ./deb-get show icaclient
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  175k    0  175k    0     0    99k      0 --:--:--  0:00:01 --:--:--   99k
Citrix Workspace app
  Package:	icaclient
  Updater:	deb-get
  Installed:	22.3.0.24
  Published:	22.3.0.24
  Architecture:	amd64
  Download:	http://downloads.citrix.com/20613/icaclient_22.3.0.24_amd64.deb?__gda__=exp=1651226310~acl=/*~hmac=177b2a403e01e0199fcb32f5e3b0fa2e995657b5c31322e07afc96e593f73cf5
  Website:	https://www.citrix.com/en-gb/downloads/workspace-app/linux
```

Many of the functions use the regex+replacement, but this won't work for this, and needs an alternative, as I have specified in the deb_icaclient function

```
local FILE="${URL##*/}"
```

### CODE REVIEW

**Comment by arif-ali** [comment]
@flexiondotorg what are your thoughts in the best way to proceed on this one.

We need the download url to be the one specified, or new one that is generated every time, otherwise the download doesn't work

**Comment by yoshimo** [comment]
Don't forget the other packages on that page.

**Comment by arif-ali** [comment]
@yoshimo which packages are you referring to?

**Comment by arif-ali** [comment]
@flexiondotorg let me know if there is anything else needs to be done here for merge

**Comment by yoshimo** [comment]
> @yoshimo which packages are you referring to?

Citrix Workspace app for Linux (x86_64)
Citrix Workspace app for Linux (x86)
Citrix Workspace app for Linux (ARM HF)

and below that
USB Support Package (x86_64)
USB Support Package (x86)
USB Support Package (ARM HF)

**Comment by arif-ali** [comment]
@yoshimo PR #245 adds the USB Support Package

**Comment by Kingeejit** [comment]
Citrix always used to required additional certificates from Firefox in order to connect via a web gateway, does anyone know if that has been resolved by Citrix themselves?

i.e.

```
sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts
sudo /opt/Citrix/ICAClient/util/ctx_rehash
```

If Citrix haven’t fixed it, that would be very helpful to add within deb-get. Does Firefox as a snap mess with those certs?

**Comment by arif-ali** [comment]
@Kingeejit that's a good call. Personally, as I manage it on my own laptop, I have a personalised salt formula, which downloads the right certs for Citrix to work. But, I am not sure `deb-get` would have the intention to do extra bits like this to resolve any cert or any post-deployment issues. 

Based on my experience, I had to download and install the following 2 certs into `/opt/Citrix/ICAClient/keystore/cacerts` to resolve issues

* https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
* https://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt.pem

I have used the Firefox snap without any issues, but personally, I just use debs where I can. I think that is probably the whole point of the `deb-get`, well it was for me anyhow.

**Comment by Kingeejit** [comment]
> Based on my experience, I had to download and install the following 2 certs into `/opt/Citrix/ICAClient/keystore/cacerts` to resolve issues
> 
> * https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
> * https://cacerts.digicert.com/DigiCertHighAssuranceEVRootCA.crt.pem

I think it’s well worth it if you can do this at installation because it benefits anyone who sets up up a _Citrix Access Gateway_. Regrettably I can’t test this anymore, but I may be able to rope someone in who can. 

> I have used the Firefox snap without any issues, but personally, I just use debs where I can. I think that is probably the whole point of the `deb-get`, well it was for me anyhow.

Sorry, I didn’t mean using the Firefox snap but glad you checked! I was referring to:

`ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts`

I wasn’t sure if Ubuntu 22.04 had a Mozilla directory if Firefox came from a snap, and how often the ca certificates were updated if Ubuntu did.

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
It is really required that download_deb() needs the 3 special cases to handle icaclient? Is it possible to handle this via deb_icaclient?

**Comment by arif-ali** [comment]
@flexiondotorg made a change, see what you think. It's a minimal type change, but then allows someone to customise the `FILE` variable.

I'll refactor/rebase it, if you are happy with this approach

**Comment by flexiondotorg** [comment]
@arif-ali That is a much nicer solution :+1: Thanks for refactoring, please rebase and I'll merge.

**Comment by natanjunges** [comment]
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

**Pull request closed without merging**
