### PR TITLE
feat: add avidemux-{cli,qt}

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Review by philclifford — DISMISSED** [review]

**Review by philclifford — COMMENTED** [review]
Is this package still maintained?  Looks like no updates since 2022 .

**Comment by rasa** [comment]
@philclifford Good question, it's definitely still [very active](https://github.com/mean00/avidemux2/graphs/contributors), with the last commit on [10/14/24](https://github.com/mean00/avidemux2/commits/master/) and the last nightly build on [9/8/24](http://www.avidemux.org/nightly/win64/), but for Windows. Not sure why they haven't cut a recent release. I can ask, if you're keen to drill into it.

**Comment by philclifford** [comment]
Worth checking as they've been cutting appimage releases and if they're not
bothering with debs any more then we can't really add them.

**Comment by rasa** [comment]
The [PPA](https://launchpad.net/~xtradeb/+archive/ubuntu/apps) is still active:
IMG_0922
but your call. We can always add them if they ever cut a new release.

**Comment by philclifford** [comment]
Ah - the PPA you linked to is not compliant with the contribution requirements: it seems to have no connection with the upstream project and appears to be a helpful 3rd-party contribution to providing a number of "missing" packages.  That's great, but on the face of it not something we can support as a source for `deb-get`.

**Comment by rasa** [comment]
@philclifford Gotcha. I wasn't aware of this requirement.

**Pull request closed without merging**
