### PR TITLE
add azure-cli

### PR DESCRIPTION
**Pull request by DavidGoodwin**
add support for the azure-cli tool.

### CODE REVIEW

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Please use `${UBUNTU_CODENAME}` instead of `lsb_release` as this will ensure compatibility with Ubuntu derivatives :+1:

**Comment by DavidGoodwin** [comment]
so it's not supported for debian variants?

**Comment by flexiondotorg** [comment]
> so it's not supported for debian variants?

Not currently.

**Comment by DavidGoodwin** [comment]
Thanks!

**Pull request merged**
