### PR TITLE
add waydroid

### PR DESCRIPTION
**Pull request by Fuseteam**
website: waydroi.id
documentation: docs.waydro.id
github: https://github.com/waydroid/waydroid

### CODE REVIEW

**Comment by Fuseteam** [comment]
yay~

**Comment by enigma9o7** [comment]
This complains about kkeys, tested on Ubuntu 22.04 and Debian 11:
```
$ sudo deb-get install waydroid
deb https://repo.waydro.id bullseye main
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://mirrors.sonic.net/debian bullseye InRelease
Hit:3 http://mirrors.sonic.net/debian bullseye-backports InRelease
Get:4 https://repo.waydro.id bullseye InRelease [1,346 B]
Hit:5 http://deb.debian.org/debian sid InRelease
Err:4 https://repo.waydro.id bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 959FE34E90E51522
Reading package lists...
W: GPG error: https://repo.waydro.id bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 959FE34E90E51522
E: The repository 'https://repo.waydro.id bullseye InRelease' is not signed.
E: Unable to locate package waydroid
$
```

**Comment by Fuseteam** [comment]
oh dear

**Comment by aleasto** [comment]
`repo.waydro.id` is moving to a docker-like naming scheme:
* debian-stable
* debian-unstable
* ubuntu-latest
* ubuntu-rolling
* ubuntu-devel

Can this work with that?

**Comment by aleasto** [comment]
> `repo.waydro.id` is moving to a docker-like naming scheme:
> 
> * debian-stable
> * debian-unstable
> * ubuntu-latest
> * ubuntu-rolling
> * ubuntu-devel
> 
> Can this work with that?

Versioned targets got restored back

**Pull request merged**
