### PR TITLE
feat: Initial support for Termius (fixes #864)

### LINKED ISSUE #864: Request to add Termius
- [Y] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Termius
 - Download URL:  https://www.termius.com/download/linux/Termius.deb
 - Website URL: https://www.termius.com/
 - App Summary: SSH, SFTP, MOSH, telnet and serial in one beautiful app

### PR DESCRIPTION
**Pull request by rasa**
First submission so feedback appreciated.

### CODE REVIEW

**Comment by rasa** [comment]
The CI failed, so I submitted this bug report to Termius' Customer Support:

Hey, I am a licensed Termius user, and submitted a GitHub PR to the deb-get project to add Termius at
https://github.com/wimpysworld/deb-get/pull/902

Unfortunately, Termius failed to install, with the error:
```
/var/lib/dpkg/info/termius-app.postinst: line 10: update-desktop-database: command not found
```
The `update-desktop-database` command is provided by the `desktop-file-utils` package, which doesn't appear to be installed in the `ubuntu-22.04` GitHub VM (actually Ubuntu 22.04.3 LTS per https://github.com/wimpysworld/deb-get/actions/runs/6434539335/job/17473961566#step:1:2 ) instance that the CI uses. 

Is issue fixable on my end, or does the .deb file need to be repackaged?

Thanks,
Ross

**Review by philclifford — CHANGES_REQUESTED** [review]
You need to match the installed app exactly or `remove` will not work. s/termius/termius-app/ in manifest and rename the package definition file to `termius-app`

**Comment by philclifford** [comment]
> Is the issue fixable on my end, or does the .deb file need to be repackaged?
> 

They really need to fix their dependency.  The CI doesn't install a desktop into the test environment, hence the lack of  `desktop-file-utils` (it is included in any of the desktop apt installation "tasks").

We need to think about improving the CI testing on several fronts. I'll add this to the issues list.  

If you rename the package file to match the application (termius-app) I see no need to wait for upstream to improve their packaging before merging this.

Thanks for your contribution.

**Comment by rasa** [comment]
@philclifford The ticket is still open in Termius' customer service portal, but no response yet. Feel free to close this if you want, and I can reopen if they ever reply.

**Comment by rasa** [comment]
> You need to match the installed app exactly or `remove` will not work. s/termius/termius-app/ in manifest and rename the package definition file to `termius-app`

@philclifford Done. Thanks for your help. Still getting up to speed here.

**Review by philclifford — APPROVED** [review]

**Pull request merged**
