### PR TITLE
added Packer

### PR DESCRIPTION
**Pull request by chriswayg**

### CODE REVIEW

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Please rebase with `main`.

**Comment by chriswayg** [comment]
> Please rebase with `main`.

Rebase has been completed.

**Comment by chriswayg** [comment]
@flexiondotorg 
> Please rebase with `main`.

Rebase has been completed.

**Review by flexiondotorg — APPROVED** [review]

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Sorry, please rebase against `main` and change `APT_KEY_URL` to `ASC_KEY_URL` as per https://github.com/wimpysworld/deb-get/commit/ceef29d454034ed0fcadcaa85c4d0092579a3bae

**Comment by natanjunges** [comment]
The format of package definitions has changed. Please read [01-main/CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) and [EXTREPO](https://github.com/wimpysworld/deb-get/blob/main/EXTREPO.md), update your implementation and submit a new PR.

**Pull request closed without merging**
