### PR TITLE
Add support to external repositories, bash completion and other quality of life improvements

### PR DESCRIPTION
**Pull request by natanjunges**
Implemented features:
- [x] External package repositories (implements #313)
- [x] Bash completion (implements #465)
- [x] Deprecated packages handling, warning about them when installed (mentioned at #295)
- [x] Optimized and filtered versions of the `list` command (`--raw`, `--installed` and `--not-installed`)
- [x] Filter outputs of `prettylist` and `csvlist` by package repository (reverts and fixes #458)
- [x] Simpler version of the `update` command (`--repos-only`) that only initializes and updates `deb-get`'s external package repositories, without updating apt or looking for updates of installed packages
- [x] Install/upgrade hooks to initialize/update package repositories
- [x] Purge hook to remove cache and package repositories
- [x] Documentation of new features and preparation of existing pertinent documentation to be moved to main package repository
- [x] Split test workflows that apply to `deb-get` and to `01-main` subfolder

### CODE REVIEW

**Comment by philclifford** [comment]
I used this (or something very like it) to move some custom user includes across:

```bash
#!/bin/bash
DGLIDESTPATH=/etc/deb-get/99-local.d
for file in /etc/deb-get.d/*; do
    tst=$(grep function "${file}")
    fn=$(basename "${file}")
    if [ "${tst/${fn}/}" == "function deb_() {" ]; then
    #the file is named exactly as the app name
        tail +2 "${file}" | grep -v -e '^}$' -e '^$' >   "${DGLIDESTPATH}/${fn}"
    else
        echo "# ERROR: File ${file} does not conform for app ${fn}"
        tst2="${tst/() {}"
        echo "# it appears to be for the app : ${tst2/function deb_}"
    fi
done
```

rough and ready and presumptive, but worked.  
A parser to pull out the main `deb_<app>() ` functions into a repository is a little more challenging, or have you got one already?

**Comment by natanjunges** [comment]
No, I created each file individually in my test repository. They are not many (186), but a script could definitely help.

**Comment by philclifford** [comment]
Definitely worth automating in case the base script gains and loses some apps.  I'll try and dig out something from the dark corners of my past lives (sure there are some self-modifying recursive nightmares lurking there but probably in C or AREXX or PROLOG ;-)  ... probably quicker to google something from stackoverflow with awk ...  
I suppose someone will be wanting `fish` completions too ...  ;-)

**Comment by natanjunges** [comment]
@philclifford or @OhMyMndy, can one of you please work in the task "Prepare pertinent test workflows to be moved to main package repository"? What is needed is to split the test workflow in two, one only with the tests of `deb-get` itself, and the other with the tests of installation of the packages. You can fork my fork and open PRs to it, so I can integrate them into this one.

**Comment by philclifford** [comment]
Happy to try. Would be good to discuss/plan in a wiki or maybe via discord when time permits

**Review by diddledani — APPROVED** [review]
I'm gonna say LGTM.

**Comment by philclifford** [comment]
I still believe https://github.com/wimpysworld/deb-get/pull/523/commits/d08c9435efd855db79b4b9ab960f0aef82dd7d40 breaks us (because 2 APT list pointing to same repo with two (albeit identical) keys makes apt upset - testing once VMs are ready.

Otherwise LGTM too - bravo!

I'll try and let all the install tests run through somewhere (also on debian) but it is noteworthy that
 * the "deb-get Tests" passes even though dpkg fails if you look at the log :shrug:
 * several apps will now fail on kinetic because repos/ppas have not built for kinetic (yet)
   *  currently that causes the list and key to be removed - maybe not ideal if there was a happy jammy repo

**Comment by natanjunges** [comment]
> I still believe [d08c943](https://github.com/wimpysworld/deb-get/commit/d08c9435efd855db79b4b9ab960f0aef82dd7d40) breaks us

Yes indeed, but I thought it was better to address that in a separate PR once this one is merged (I'm thinking on a solution with hard links, since they have built-in reference counting, but there might be better ones). Then we can work on the ideas we discussed for `apt`-like `depends`, `conflicts` and `replaces` as well.

>     * the "deb-get Tests" passes even though dpkg fails if you look at the log shrug

Where? I only found an `ls` error, but it is harmless (ideally it should be silenced).

>     * several apps will now fail on kinetic because repos/ppas have not built for kinetic (yet)

This does not concern this PR, but we will indeed need to address it, ideally before the next release of `deb-get`.

>       * currently that causes the list and key to be removed - maybe not ideal if there was a happy jammy repo

We should also try to come up with a better solution in a separate PR, something in the lines of #603.

**Comment by philclifford** [comment]
> Yes indeed, but I thought it was better to address that in a separate PR once this one is merged

Fine with that : we should perhaps add a note somewhere that 6.1 users must uninstall 6.1 before installing 7.0

**Comment by philclifford** [comment]
> Where? I only found an `ls` error, but it is harmless (ideally it should be silenced).

Sorry - mea culpa.  Looks like I was confused (how unusual!)  - Only seeing the `ls` now: I did see a dpkg fail in a test that passed, but was thrashing around in the early hours and mis-remembered after sleeping.

**Review by philclifford — APPROVED** [review]
https://github.com/philclifford/deb-get/actions/runs/3331912181
[deb-get Tests](https://github.com/philclifford/deb-get/actions/workflows/tests-deb-get.yml)

LGTM

**Comment by OhMyMndy** [comment]
Really cool to see some big progress on `deb-get`! One thing, which isn't possible any more, is to just grab the `deb-get` file from the repo and execute it because it depends on many other files. Reason why I used `deb-get` like that is to use the version from my pull request because it wasn't merged yet (I wanted to install something with `deb-get` which was not upstream yet).

This setup resolves that problem by allowing external repo's!

Great work @natanjunges @philclifford @diddledani

**Review by flexiondotorg — APPROVED** [review]

**Pull request merged**
