### PR TITLE
Fixes 658 - add Trilium Notes

### PR DESCRIPTION
**Pull request by p4p4j0hn**
Fixes [#658](https://github.com/wimpysworld/deb-get/issues/658)
Add support for installing Trilium Notes.

### CODE REVIEW

**Comment by philclifford** [comment]
Fixes #658 
@p4p4j0hn if you put that in your comment it will auto-close and link to the issue

**Comment by p4p4j0hn** [comment]
@philclifford Did I add that correctly?

**Comment by philclifford** [comment]
@p4p4j0hn yes (although better in a line alone, and if you ever need to close more than one issue or PR with one merge they need to be separately mentioned one per line)  You can see over there :arrow_upper_right: a link has appeared, and a back-reference one will be at the other end.  Helpful stuff, and also a boon to maintainers. Thanks

**Comment by p4p4j0hn** [comment]
Thanks for the tips/mentorship @philclifford :smile:

**Review by philclifford — APPROVED** [review]
LGTM
(in fact worked most excellently)

**Comment by philclifford** [comment]
You're most welcome. Thanks for the contribution!

**Pull request merged**
