### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by lefterisgar**
* Add description for `deborah`
* Update description for `limoji`

**Please squash the commits before merging.** I'm sorry but my repo was a bit messed up.

### CODE REVIEW

**Comment by natanjunges** [comment]
The README file is not supposed to be updated manually, but using the `cog` tool. Check [CONTRIBUTING](../blob/main/CONTRIBUTING.md#updating-readmemd) for further instructions.

**Comment by kz6fittycent** [comment]
> The README file is not supposed to be updated manually, but using the `cog` tool. Check [CONTRIBUTING](../blob/main/CONTRIBUTING.md#updating-readmemd) for further instructions.

Unfortunately, the cog tool doesn't seem to be working, at least for me and potentially others. Is manually editing acceptable if this is the case?

**Comment by natanjunges** [comment]
What is happening with `cog`? If it is having issues, we should look for a solution. But instead of manually editing the `README` file (i.e. writing it yourself), you should do what the `cog` script would, which is to run `deb-get prettylist` and paste the result between `]]] -->` (line 154) and `<!-- [[[end]]] -->`.

**Comment by natanjunges** [comment]
#544 should fix it.

**Comment by kz6fittycent** [comment]
> #544 should fix it.

Yep that got it!

**Comment by natanjunges** [comment]
Please rebase with main.

**Review by natanjunges — CHANGES_REQUESTED** [review]
Please rebase with main.

**Pull request closed without merging**
