### PR TITLE
Exifcleaner

### PR DESCRIPTION
**Pull request by zero77**
https://github.com/wimpysworld/deb-get/issues/667

### CODE REVIEW

**Comment by philclifford** [comment]
If you had used an appropriate keyword when referencing the issue it could have been closed automatically ... :bulb:

**Comment by zero77** [comment]
> If you had used an appropriate keyword when referencing the issue it could have been closed automatically ... 💡

What do you mean by use appropriate keyword

**Comment by philclifford** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

So 
Closes #667 
or
Resolves #667 
in your comment would have linked the PR (shown up on the right at the PR and on the issue as a link not just a mention), and automatically closed the issue on successful merge.

**Comment by zero77** [comment]
Thanks for the explanation, i will do this from now on.

**Pull request merged**
