### PR TITLE
fix: bitwig-studio has in-housed downloads

### LINKED ISSUE #1078: Cannot update and upgrade apps after bitwig-studio including
## Reporting a bug 🐛

Cannot update and upgrade apps after (alphabetically) bitwig-studio including.

### Expected behavior

`deb-get update` runs successfully and `deb-get list` shows full list of supported apps

### Actual behavior

An error occures after few seconds after `deb-get update`
```$ deb-get update --repos-only
  [+] Updating /etc/deb-get/01-main
 -=O#- #   #    #                                                              
$   [+] Updating cache of supported apps in the background
  [!] ERROR! Missing required information of website package bitwig-studio:
URL=
VERSION_PUBLISHED=
```

### Steps to reproduce

Add DEBGET_TOKEN and just run `deb-get update`

### System information

Run the following a paste the output below:

#### /etc/os-release

```bash
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### /etc/lsb-release

```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

#### deb-get version

```bash
0.4.0
```

### PR DESCRIPTION
**Pull request by philclifford**
closes #1078

### CODE REVIEW

**Comment by philclifford** [comment]
Ah - redirects no longer working!

**Comment by philclifford** [comment]
Test failure is curious: I guess they're missing a dependency that I have installed. It installed with out issue on this 22.04 potato.

``` text
BitWig Studio
  Package:	bitwig-studio
  Repository:	99-local
  Updater:	deb-get
  Installed:	5.1.9
  Published:	5.1.9
```

**Comment by philclifford** [comment]
removing it suggest why the test might have failed

```
The following packages will be REMOVED
bitwig-studio libxcb-icccm4:i386 libxcb-util1:i386 libxcb-xinput0:i386 libxcb-xkb1:i386 libxkbcommon-x11-0:i386
```
I bet it's those 32-bit packages and the runner not being able/configured to support i386

**Review by flexiondotorg — APPROVED** [review]

**Comment by flexiondotorg** [comment]
Adding `dpkg --add-architecture i386` before the tests run should sort that.

**Pull request merged**
