### PR TITLE
Added thinlinc specification file

### PR DESCRIPTION
**Pull request by diegobersanetti**
[ThinLinc](https://www.cendio.com/thinlinc) is a software that enables organizations to implement a Linux server-based computing (SBC) infrastructure.

I added the thinlinc specification file and tested it with the new version released today (amd64 arch only).

### CODE REVIEW

**Comment by philclifford** [comment]
please rename the specification file to match the package name in the .deb (`thinlinc-client` ) and also add it to the `manifest`.  You might also like to use their description as well : 
```
apt info -f  ./thinlinc-client_4.15.0-3258_amd64.deb
Package: thinlinc-client
Version: 4.15.0-3258
...
Description: ThinLinc Client
 The ThinLinc Client is a remote desktop client used to connect to a ThinLinc
```

**Review by philclifford — CHANGES_REQUESTED** [review]
please rename the specification file to match the package name in the .deb (thinlinc-client ) and also add it to the manifest. You might also like to use their description as well :

apt info -f  ./thinlinc-client_4.15.0-3258_amd64.deb
Package: thinlinc-client
Version: 4.15.0-3258
...
Description: ThinLinc Client
 The ThinLinc Client is a remote desktop client used to connect to a ThinLinc

**Comment by diegobersanetti** [comment]
Hello,

I committed the requested changes, now it should be ok, thanks for the input!

One additional thing that I noticed but I don't know if it is relevant: when I do a "deb-get update", the line relative to thinlinc-client shows a html file, not a json:

`[+] Updating /var/cache/deb-get/thinlinc-client.html`

**Comment by philclifford** [comment]
> One additional thing that I noticed but I don't know if it is relevant: when I do a "deb-get update", the line relative to thinlinc-client shows a html file, not a json:

That's normal for website sources. The json cache is the result of the GitHub API. 

Thanks.

**Review by philclifford — APPROVED** [review]

**Pull request merged**
