### PR TITLE
Added support for Novelwriter

### LINKED ISSUE #666: Add novelWriter
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: novelWriter
 - Download URL: https://github.com/vkbo/novelWriter/releases
 - Website URL: https://novelwriter.io/
 - App Summary: A markdown-like text editor designed for writing novels and larger projects of many smaller plain text documents. It is designed to be a simple text editor that allows for easy organisation of text files and notes, with a meta data syntax for comments, synopsis, and cross-referencing between files, and built on plain text files for robustness.

### PR DESCRIPTION
**Pull request by dchurch315**
Added support to pull from novelwriter github releases. Thanks for feedback @philclifford 

closes #666

### CODE REVIEW

**Review by philclifford — APPROVED** [review]

**Comment by vkbo** [comment]
Hi, the author of novelWriter here. Thanks for adding it, but I'd like to point out that it isn't a "markdown editor for novels". It only uses a subset of markdown, mixed in with other syntax styles. The repo uses the following description:

> novelWriter is an open source plain text editor designed for writing novels. It supports a minimal markdown-like syntax for formatting text. It is written with Python 3 (3.9+) and Qt 5 (5.15) for cross-platform support.

**Comment by philclifford** [comment]
Hi @vkbo ! Thanks for the correction, I'm sorry the misdescription got through - I'll try and get it corrected. Also thanks for novelWriter!

**Comment by vkbo** [comment]
Thanks for responding, even if I posted in an old PR. I get requests from people who expect full markdown support, so I'd like to avoid adding to the expectation that it is a full markdown editor!

**Comment by philclifford** [comment]
@vkbo I hope you find #1082 acceptable.

**Pull request merged**
