### PR TITLE
Add mantic and noble support

### PR DESCRIPTION
**Pull request by philclifford**
and remove kinetic where it is not explicitly available upstream and the latest release mentioned there

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@philclifford Please rebase this and include support for Noble

**Review by flexiondotorg — CHANGES_REQUESTED** [review]
Rebase required and with Noble release approaching, probably good to add support for Noble.

**Comment by philclifford** [comment]
Working through revisiting upstreams ...

 - [ ] firefox-devedition
 - [ ] beersmith3
 - [ ] winehq-staging
 - [ ] nala
 - [x] nala-legacy ( obv. n/a )
 - [ ] azure-cli
 - [x] waydroid
 - [ ] openrgb
 - [ ] filezilla-theme-papirus
 - [ ] quickobs
 - [ ] stremio
 - [ ] battery-monitor
 - [ ] simple-pwgen
 - [ ] sunshine
 - [ ] onedriver
 - [ ] firefox
 - [ ] virtualbox-6.1
 - [ ] doublecmd-qt
 - [ ] files-cli
 - [ ] flameshot
 - [ ] librewolf
 - [ ] media-downloader
 - [ ] vagrant
 - [ ] i3
 - [ ] deborah
 - [ ] virtualbox-7.0
 - [ ] firefox-nightly
 - [ ] winehq-devel
 - [ ] master-pdf-editor-5
 - [ ] mergerfs
 - [ ] cronopete
 - [ ] atuin
 - [ ] winehq-stable
 - [ ] firefox-esr
 - [ ] firefox-beta
 - [ ] papirus-folders
 - [ ] jellyfin-media-player
 - [ ] doublecmd-gtk

**Comment by philclifford** [comment]
@flexiondotorg I've rebased and added some noble support added along with other corrections where checking revealed upstream support changed.
I suggest separately removing/deprecating `flameshot`  even though I love/use it since it hasn't been touched in a few years.
The remainder of the checklist I'll try and finish later (or also happy to do them in a later PR )

**Pull request merged**
